[workspace]
resolver = "2"
members = ["tools/steel-check", "steelctl"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.74"
license = "GPL-3.0-or-later"
repository = "https://github.com/ChaseSunstrom/steel-os"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true
